version: '3.8'

services:
  app:
    build: .
    container_name: atendimento-app
    volumes:
      - .:/var/www
    networks:
      - db-network
  mysql-laravel:
    image: mysql:8.0
    container_name: mysql-laravel
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: almoxarifadoCoren
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-laravel:/var/lib/mysql
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  mysql-data-laravel: